alertmanager:
  priorityClassName: "stable-service-priority"
  persistentVolume:
    enabled: true

pushgateway:
  priorityClassName: "stable-service-priority"
  persistentVolume:
    enabled: true

server:
  priorityClassName: "stable-service-priority"
  persistentVolume:
    enabled: true
    size: 100Gi

  ingress:
    enabled: true
    hosts:
    - prometheus.simulation.deeproute.ai

nodeExporter:
  priorityClassName: "stable-service-priority"
  tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  - key: web-server
    operator: Equal
    value: "true"
    effect: NoSchedule
