- name: Ensure dependencies are installed.
  apt:
    state: present
    pkg:
      - cpufrequtils

- name: Copy Script to Remote Machine
  template:
    src: "usr/local/bin/set-cpu-performance.sh"
    dest: /usr/local/bin/set-cpu-performance.sh
    owner: root
    group: root
    mode: 0777   

- name: Copy system file to Remote Machine
  template:
    src: "lib/systemd/system/cpu-performance.service"
    dest: /lib/systemd/system/cpu-performance.service
    owner: root
    group: root
    mode: 0777       

- name: Enable service cpu-performance 
  systemd:
    name: cpu-performance 
    enabled: true  
    daemon_reload: true

- name: Enable service cpu-performance 
  systemd:
    name: cpu-performance 
    enabled: true  
    daemon_reload: true    

- name: Start service cpu-performance 
  systemd:
    name: cpu-performance 
    state: started   

- name: Check current cpu performance mode
  shell:
    cmd: |
      cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor|grep 'performance'     