- hosts: "{{ host }}"
  #remote_user: deeproute
  become: true
  become_method: sudo
  gather_facts: false
  vars:
    - devops_password: 'Qjgj1b9@123'
    - ansible_ssh_private_key_file: "~/.ssh/devops_key"
  tasks:
  - name: Add a new user named devops
    user:
      name: devops
      shell: /bin/bash
      password: "{{ devops_password | password_hash('sha512') }}"
      update_password: on_create
  - name: Add devops user to the sudoers
    copy:
      dest: "/etc/sudoers.d/devops"
      content: "devops  ALL=(ALL)  NOPASSWD: ALL"
  - name: Deploy SSH Key
    authorized_key: 
      user=devops
      key="{{ item }}"
      state=present
    with_file:
      - public_keys/devops.pub
  - name: Disable Password Authentication
    lineinfile:
      dest=/etc/ssh/sshd_config
      regexp='^PasswordAuthentication'
      line="PasswordAuthentication no"
      state=present
      backup=yes
  - name: Disable GSS Authentication
    lineinfile:
      dest=/etc/ssh/sshd_config
      regexp='^GSSAPIAuthentication'
      line="GSSAPIAuthentication no"
      state=present
      backup=yes
  - name: Disable UseDNS
    lineinfile:
      dest=/etc/ssh/sshd_config
      regexp='^UseDNS'
      line="UseDNS no"
      state=present
      backup=yes
  - name: Disable Root Login
    lineinfile:
      dest=/etc/ssh/sshd_config
      regexp='^PermitRootLogin'
      line="PermitRootLogin no"
      state=present
      backup=yes
  - name: restart ssh
    service:
      name=sshd
      state=restarted
