- name: Add entry to /etc/apt/sources.list if not already present
  blockinfile: 
    state: present
    dest: /etc/apt/sources.list
    marker: "# add apt source ANSIBLE MANAGED BLOCK {mark}"
    block: |
      deb https://apt.deeproute.cn/docker-ce-focal/ focal edge nightly stable test

- name: Add deeproute source apt-key
  shell:
    cmd: |
      curl -fsSL https://apt.deeproute.cn/key/deeproute | apt-key add -
  register: aptkey_result

- name: Check docker running specify version
  shell:
    cmd: |
      docker version|grep 'Version:           25.0.5'
  ignore_errors: true
  register: docker_exists

- name: Check docker running
  shell:
    cmd: |
      docker version
  ignore_errors: true
  register: docker_running

- name: Create docker config dir
  shell:
    cmd: |
      mkdir -p /etc/docker

- name: Copy daemon.json file to Remote Machine
  template:
    src: "etc/docker/daemon.json"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify:
    - reload docker

- name: Install docker no install containerd
  shell:
    cmd: |
      apt update
      # 保留已经安装的containerd版本
      echo "N" |apt-get install --no-install-recommends docker-ce=5:25.0.5-1~ubuntu.20.04~focal docker-ce-cli=5:25.0.5-1~ubuntu.20.04~focal docker-buildx-plugin=0.13.1-1~ubuntu.20.04~focal -y
  when: aptkey_result.rc == 0 and docker_exists.rc != 0

- name: Install docker no install containerd
  shell:
    cmd: |
      apt update
      # 保留已经安装的containerd版本
      echo "Y" |apt-get install --no-install-recommends docker-ce=5:25.0.5-1~ubuntu.20.04~focal docker-ce-cli=5:25.0.5-1~ubuntu.20.04~focal docker-buildx-plugin=0.13.1-1~ubuntu.20.04~focal
  when: aptkey_result.rc == 0 and docker_running.rc != 0

handlers:
- name: reload docker
  service:
    name=docker
    state=reloaded  